version: '3.8'
name: 'cascade_dash_frontend_dev'

services:
  frontend:
    stdin_open: true
    tty: true
    build:
      dockerfile: ./dev.Dockerfile
      context: ../../
    volumes:
      - '../../:/app'
    ports:
      - '3000:3000'
