# linting workflow 
#  - runs npm run lint on the project

name: linting

on: pull_request

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'
    - name: Install dependencies
      run: npm ci
      env:
        CI: TRUE
    - name: Run ESLint Report
      run: npm run lint:report
      # continue on error, so it still reports it in the next step
      continue-on-error: true
    - name: Annotate Code Linting Results
      uses: ataylorme/eslint-annotate-action@v2
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        report-json: "eslint_report.json"
